apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ include "nginx-logging-cw-demo.fullname" . }}-output
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nginx-logging-cw-demo.labels" . | indent 4 }}
spec:
  cloudwatch:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          name: logging-cloudwatch
          key: accesskey
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          name: logging-cloudwatch
          key: secretkey
    log_group_name: {{ .Values.aws.log_group_name }}
    log_stream_name: {{ .Values.aws.log_stream_name }}
    region: {{ .Values.aws.region }}
    auto_create_stream: true
    buffer:
      timekey: 30s
      timekey_wait: 30s
      timekey_use_utc: true
