apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: file-output-sample
spec:
spec:
  file:
    path: /tmp/logs/
    buffer:
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true
