apiVersion: logging.banzaicloud.com/v1alpha2
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  outputRefs:
    - gcs-output-sample
    - s3-output-example
  selectors:
    app: nginx
