apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: loggingplugins.logging.banzaicloud.com
spec:
  group: logging.banzaicloud.com
  names:
    kind: LoggingPlugin
    listKind: LoggingPluginList
    plural: loggingplugins
    singular: loggingplugin
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
