apiVersion: logging.banzaicloud.com/v1alpha2
kind: ClusterFlow
metadata:
  name: {{ include "nginx-logging-es-demo.fullname" . }}-es-flow
  namespace: logging-system
  labels:
    app: {{ include "nginx-logging-es-demo.name" . }}
    chart: {{ include "nginx-logging-es-demo.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  filters:
    - tag_normaliser: {}
  selectors: {}
  outputRefs:
    - {{ include "nginx-logging-es-demo.fullname" . }}-es-output
