apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logging-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logging-operator
    spec:
      containers:
        - name: logging-operator
<<<<<<< HEAD
          image: "banzaicloud/logging-operator:2.1.1"
=======
          image: "banzaicloud/logging-operator:2.1.0"
>>>>>>> Add ES params
          imagePullPolicy: IfNotPresent
          resources:
            {}
      serviceAccountName: logging-operator
