apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logging-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logging-operator
    spec:
      containers:
        - name: logging-operator
          image: "banzaicloud/logging-operator:2.1.0"
          imagePullPolicy: IfNotPresent
          resources:
            {}

          ports:
            - name: http
              containerPort: 8080
      serviceAccountName: logging-operator
