kind: ConfigMap
apiVersion: v1
metadata:
  name: "logging-operator-config"
  labels:
    app:  "logging-operator"
data:
  config.toml: |-
    # This is the example config for the logging operator

    [logging-operator]
    rbac = false
    namespace = "default"

    [fluent-bit]
    enabled = true
    namespace = "default"
    tls_enabled = true

    [fluentd]
    enabled = true
    namespace = "default"
    tls_enabled = true