apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
    
        sendfile on;
    
        default_type application/octet-stream;
    
        gzip on;
        gzip_http_version 1.1;
        gzip_disable      "MSIE [1-6]\.";
        gzip_min_length   256;
        gzip_vary         on;
        gzip_proxied      expired no-cache no-store private auth;
        gzip_types        text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_comp_level   9;
    
        root /usr/share/nginx/html;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        location /301 {
            return 301 'gangnam style!';
        }
        location /302 {
            return 302 'gangnam style!';
        }
    
        location /400 {
            return 400 'gangnam style!';
        }
        location /401 {
            return 401 'gangnam style!';
        }
        location /402 {
            return 402 'gangnam style!';
        }
        location /403 {
            return 403 'gangnam style!';
        }
    
        location /500 {
            return 500 'gangnam style!';
        }
        location /501 {
            return 501 'gangnam style!';
        }
        location /502 {
            return 502 'gangnam style!';
        }
        location /503 {
            return 503 'gangnam style!';
        }
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  script.sh: |-
    #!/bin/bash
    set -euo pipefail
    apt-get update > /dev/null
    apt-get install -y curl > /dev/null
    paths=(/ /301 /302 /400 /401 /402 /403 /500 /501 /502 /503)
    while :
    do
        path=${paths[$RANDOM % ${#paths[@]}]}
    	curl -s localhost$path > /dev/null
    	sleep 2
    done
