apiVersion: v1
kind: Namespace
metadata:
  name: custom
---
apiVersion: logging.banzaicloud.com/v1alpha2
kind: Flow
metadata:
  name: flow-sample
spec:
  selectors:
    sampleKey: sampleValue
  filters:
    - stdout: {}
  outputRefs:
    - "output-sample"
