apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: customlogging
spec:
  fluentd: {}
  fluentbit:
    image:
      repository: fluent/fluent-bit
      tag: 1.3.2-debug
      pullPolicy: Always
  controlNamespace: logging

