apiVersion: v1
kind: Namespace
metadata:
  name: control
---
apiVersion: logging.banzaicloud.com/v1alpha2
kind: ClusterOutput
metadata:
  name: output-custom-cluster
  namespace: control
spec:
  loggingRef: customref
  nullout: {}