apiVersion: v1
appVersion: "2.7.0"
description: A Helm chart for Kubernetes
name: logging-demo
version: 2.7.0
icon: https://raw.githubusercontent.com/banzaicloud/logging-operator/master/docs/img/icon.png
