apiVersion: v1
appVersion: "3.1.0-rc1"
description: A Helm chart for Kubernetes
name: logging-demo
version: 3.0.1
icon: https://raw.githubusercontent.com/banzaicloud/logging-operator/master/docs/img/icon.png
